import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'inward_data_processor.dart';

class InwardPrintService {
  Future<Uint8List> generatePdfBytes(Map<String, dynamic> inward) async {
    final pdf = await _buildPdf(inward);
    return pdf.save();
  }

  Future<void> printInwardReport(Map<String, dynamic> inward) async {
    final pdf = await _buildPdf(inward);

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Lot_Inward_${inward['lotNo']}',
    );
  }

  Future<pw.Document> _buildPdf(Map<String, dynamic> inward) async {
    final pdf = pw.Document();

    final font = pw.Font.helvetica();
    final boldFont = pw.Font.helveticaBold();

    final data = InwardDataProcessor.process(inward);
    final dias = data['dias'] as List<String>;
    final rows = data['rows'] as List<Map<String, dynamic>>;
    final totals = data['totals'] as Map<String, dynamic>;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4.landscape,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader(inward, boldFont),
              pw.SizedBox(height: 20),
              _buildTable(dias, rows, totals, font, boldFont),
              pw.Spacer(),
              _buildFooter(boldFont),
            ],
          );
        },
      ),
    );
    
    return pdf;
  }

  pw.Widget _buildHeader(Map<String, dynamic> inward, pw.Font boldFont) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'LOT INWARD REPORT',
              style: pw.TextStyle(font: boldFont, fontSize: 18),
            ),
            pw.Text('Party: ${inward['fromParty']}'),
            pw.Text('Lot Name: ${inward['lotName']}'),
          ],
        ),
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.end,
          children: [
            pw.Text('Date: ${DateFormat('dd-MM-yyyy').format(DateTime.parse(inward['inwardDate']))}'),
            pw.Text('Lot No: ${inward['lotNo']}'),
            pw.Text('Ref/DC: ${inward['partyDcNo'] ?? 'N/A'}'),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildTable(
    List<String> dias,
    List<Map<String, dynamic>> rows,
    Map<String, dynamic> totals,
    pw.Font font,
    pw.Font boldFont,
  ) {
    // Headers: Colour, [Dia 1], [Dia 2]..., Total Rolls, Total Weight
    // For each Dia column, we might want sub-columns (Rolls | Wt) or just stack them?
    // The user sample shows distinct columns for each DIA.
    // Let's assume typical Matrix: 30 DIA, 32 DIA, etc.
    // Each DIA cell needs to show Rolls & Weight? Or just Weight?
    // Sample says: "30 DIA", "32 DIA".
    // Under 30 DIA: "5 / 96.315" (Rolls / Weight).
    
    final headers = [
      'Colour',
      ...dias.map((d) => '$d DIA'),
      'Total Rolls',
      'Total Wt',
    ];

    return pw.Table.fromTextArray(
      headers: headers,
      data: [
        ...rows.map((row) {
          return [
            row['colour'],
            ...dias.map((dia) {
               final cell = row['data'][dia] ?? {'rolls': 0, 'weight': 0.0};
               if (cell['rolls'] == 0 && cell['weight'] == 0) return '-';
               return '${cell['rolls']} / ${cell['weight'].toStringAsFixed(2)}';
            }),
            row['totalRolls'].toString(),
            row['totalWeight'].toStringAsFixed(2),
          ];
        }),
        // Grand Total Row
        [
          'TOTAL',
          ...dias.map((dia) {
             final t = totals[dia] ?? {'rolls': 0, 'weight': 0.0};
             return '${t['rolls']} / ${t['weight'].toStringAsFixed(2)}';
          }),
          totals['grandTotalRolls'].toString(),
          totals['grandTotalWeight'].toStringAsFixed(2),
        ]
      ],
      headerStyle: pw.TextStyle(font: boldFont, fontWeight: pw.FontWeight.bold),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
      cellStyle: pw.TextStyle(font: font, fontSize: 10),
      cellAlignment: pw.Alignment.center,
      border: pw.TableBorder.all(),
    );
  }

  pw.Widget _buildFooter(pw.Font boldFont) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text('Generated by Garments App', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
        pw.Text('Authorized Signature', style: pw.TextStyle(font: boldFont)),
      ],
    );
  }

}
